apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: application-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Application is the Schema for the applications API
      displayName: Application
      kind: Application
      name: applications.api.app.op
      version: v1alpha1
  description: This operator automates the process of deploying as Kubernetes Deployment
    and exposing the same as a Kubernetes service.
  displayName: Application Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubernetes
  - operator
  - automation
  - devops
  - containers
  links:
  - name: Application Operator
    url: https://application-operator.domain
  maintainers:
  - email: sayedimran00786@gmail.com
    name: sayed-imran
  maturity: alpha
  provider:
    name: Sayed Imran
    url: https://www.linkedin.com/in/sayed-imran/
  version: 0.0.0
